FROM node:10-alpine as builder

WORKDIR /app
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .

RUN npm run build

FROM node:10-alpine

WORKDIR /app
VOLUME [ "/app/uploads" ]

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY --from=builder /app/build ./build

CMD node build/index.js