# creamos un primer contenedor y le damos un nombre 'builder'
FROM node:10-alpine as builder

WORKDIR /app

COPY ./package.json ./package.json

RUN npm install

# construimos nuestra app
RUN npm run build

# creamos un nuevo contenedor limpio
FROM node:10-alpine

WORKDIR /app

# copiamos los ficheros que necesitamos para arrancar la aplicación desde
# el contenedor donde hemos construido la app builder
COPY --from=builder /app/build/index.js ./index.js

EXPOSE 8080

CMD node ./index.js
