FROM node:10-alpine as builder

WORKDIR /app
COPY ./package.json ./package.json

RUN npm install

RUN npm run build

FROM node:10-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY ./src/index.js ./build/index.js

EXPOSE 8080

CMD node ./build/index.js